/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InvestissementRouteImport } from './routes/investissement'
import { Route as DonneesBrvmRouteImport } from './routes/donnees-brvm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ApplicationsSamamenuRouteImport } from './routes/applications.samamenu'
import { Route as ApplicationsNdeyPharmaRouteImport } from './routes/applications.ndey-pharma'
import { Route as ApplicationsLifeEstudiantinRouteImport } from './routes/applications.life-estudiantin'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as ApiPublicHooksBrvmPollRouteImport } from './routes/api/public/hooks/brvm-poll'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestissementRoute = InvestissementRouteImport.update({
  id: '/investissement',
  path: '/investissement',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesBrvmRoute = DonneesBrvmRouteImport.update({
  id: '/donnees-brvm',
  path: '/donnees-brvm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRoute,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActualitesRoute,
} as any)
const ApplicationsSamamenuRoute = ApplicationsSamamenuRouteImport.update({
  id: '/samamenu',
  path: '/samamenu',
  getParentRoute: () => ApplicationsRoute,
} as any)
const ApplicationsNdeyPharmaRoute = ApplicationsNdeyPharmaRouteImport.update({
  id: '/ndey-pharma',
  path: '/ndey-pharma',
  getParentRoute: () => ApplicationsRoute,
} as any)
const ApplicationsLifeEstudiantinRoute =
  ApplicationsLifeEstudiantinRouteImport.update({
    id: '/life-estudiantin',
    path: '/life-estudiantin',
    getParentRoute: () => ApplicationsRoute,
  } as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActualitesRoute,
} as any)
const ApiPublicHooksBrvmPollRoute = ApiPublicHooksBrvmPollRouteImport.update({
  id: '/api/public/hooks/brvm-poll',
  path: '/api/public/hooks/brvm-poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/donnees-brvm': typeof DonneesBrvmRoute
  '/investissement': typeof InvestissementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/applications/life-estudiantin': typeof ApplicationsLifeEstudiantinRoute
  '/applications/ndey-pharma': typeof ApplicationsNdeyPharmaRoute
  '/applications/samamenu': typeof ApplicationsSamamenuRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/api/public/hooks/brvm-poll': typeof ApiPublicHooksBrvmPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/donnees-brvm': typeof DonneesBrvmRoute
  '/investissement': typeof InvestissementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/applications/life-estudiantin': typeof ApplicationsLifeEstudiantinRoute
  '/applications/ndey-pharma': typeof ApplicationsNdeyPharmaRoute
  '/applications/samamenu': typeof ApplicationsSamamenuRoute
  '/actualites': typeof ActualitesIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/api/public/hooks/brvm-poll': typeof ApiPublicHooksBrvmPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/donnees-brvm': typeof DonneesBrvmRoute
  '/investissement': typeof InvestissementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/applications/life-estudiantin': typeof ApplicationsLifeEstudiantinRoute
  '/applications/ndey-pharma': typeof ApplicationsNdeyPharmaRoute
  '/applications/samamenu': typeof ApplicationsSamamenuRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/api/public/hooks/brvm-poll': typeof ApiPublicHooksBrvmPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admin'
    | '/applications'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/donnees-brvm'
    | '/investissement'
    | '/mentions-legales'
    | '/services'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/applications/life-estudiantin'
    | '/applications/ndey-pharma'
    | '/applications/samamenu'
    | '/actualites/'
    | '/applications/'
    | '/api/public/hooks/brvm-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/donnees-brvm'
    | '/investissement'
    | '/mentions-legales'
    | '/services'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/applications/life-estudiantin'
    | '/applications/ndey-pharma'
    | '/applications/samamenu'
    | '/actualites'
    | '/applications'
    | '/api/public/hooks/brvm-poll'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admin'
    | '/applications'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/donnees-brvm'
    | '/investissement'
    | '/mentions-legales'
    | '/services'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/applications/life-estudiantin'
    | '/applications/ndey-pharma'
    | '/applications/samamenu'
    | '/actualites/'
    | '/applications/'
    | '/api/public/hooks/brvm-poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DonneesBrvmRoute: typeof DonneesBrvmRoute
  InvestissementRoute: typeof InvestissementRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksBrvmPollRoute: typeof ApiPublicHooksBrvmPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investissement': {
      id: '/investissement'
      path: '/investissement'
      fullPath: '/investissement'
      preLoaderRoute: typeof InvestissementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees-brvm': {
      id: '/donnees-brvm'
      path: '/donnees-brvm'
      fullPath: '/donnees-brvm'
      preLoaderRoute: typeof DonneesBrvmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/applications/samamenu': {
      id: '/applications/samamenu'
      path: '/samamenu'
      fullPath: '/applications/samamenu'
      preLoaderRoute: typeof ApplicationsSamamenuRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/applications/ndey-pharma': {
      id: '/applications/ndey-pharma'
      path: '/ndey-pharma'
      fullPath: '/applications/ndey-pharma'
      preLoaderRoute: typeof ApplicationsNdeyPharmaRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/applications/life-estudiantin': {
      id: '/applications/life-estudiantin'
      path: '/life-estudiantin'
      fullPath: '/applications/life-estudiantin'
      preLoaderRoute: typeof ApplicationsLifeEstudiantinRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/api/public/hooks/brvm-poll': {
      id: '/api/public/hooks/brvm-poll'
      path: '/api/public/hooks/brvm-poll'
      fullPath: '/api/public/hooks/brvm-poll'
      preLoaderRoute: typeof ApiPublicHooksBrvmPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActualitesRouteChildren {
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
}

const ActualitesRouteChildren: ActualitesRouteChildren = {
  ActualitesSlugRoute: ActualitesSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
}

const ActualitesRouteWithChildren = ActualitesRoute._addFileChildren(
  ActualitesRouteChildren,
)

interface ApplicationsRouteChildren {
  ApplicationsLifeEstudiantinRoute: typeof ApplicationsLifeEstudiantinRoute
  ApplicationsNdeyPharmaRoute: typeof ApplicationsNdeyPharmaRoute
  ApplicationsSamamenuRoute: typeof ApplicationsSamamenuRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsLifeEstudiantinRoute: ApplicationsLifeEstudiantinRoute,
  ApplicationsNdeyPharmaRoute: ApplicationsNdeyPharmaRoute,
  ApplicationsSamamenuRoute: ApplicationsSamamenuRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRouteWithChildren,
  AdminRoute: AdminRoute,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DonneesBrvmRoute: DonneesBrvmRoute,
  InvestissementRoute: InvestissementRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksBrvmPollRoute: ApiPublicHooksBrvmPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
